import type { Metadata } from "next";

import "./globals.css";
import "./style.module.css"
import { Orbitron } from 'next/font/google'
const orbitron = Orbitron({
  subsets: ['latin'],
  variable: '--font-orbitron',
})


export const metadata: Metadata = {
  title: "validate.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={orbitron.variable}>{children}</body>
    </html>
     
  );
}
